
// This file has been generated by the GUI designer. Do not modify.
namespace GTKFrontend
{
	public partial class NewModDialog
	{
		private global::Gtk.Table table1;

		private global::Gtk.Entry authorentry;

		private global::Gtk.Label authorlabel;

		private global::Gtk.Entry descriptionentry;

		private global::Gtk.Label descriptionlabel;

		private global::Gtk.Entry titleentry;

		private global::Gtk.Label titlelabel;

		private global::Gtk.Entry updateurlentry;

		private global::Gtk.Label updateurllabel;

		private global::Gtk.Entry urlentry;

		private global::Gtk.Label urllabel;

		private global::Gtk.Entry versionentry;

		private global::Gtk.Label versionlabel;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKFrontend.NewModDialog
			this.Name = "GTKFrontend.NewModDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("New Mod");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child GTKFrontend.NewModDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.authorentry = new global::Gtk.Entry();
			this.authorentry.CanFocus = true;
			this.authorentry.Name = "authorentry";
			this.authorentry.IsEditable = true;
			this.authorentry.InvisibleChar = '•';
			this.table1.Add(this.authorentry);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.authorentry]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.authorlabel = new global::Gtk.Label();
			this.authorlabel.Name = "authorlabel";
			this.authorlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Author:");
			this.authorlabel.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.authorlabel);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.authorlabel]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.descriptionentry = new global::Gtk.Entry();
			this.descriptionentry.CanFocus = true;
			this.descriptionentry.Name = "descriptionentry";
			this.descriptionentry.IsEditable = true;
			this.descriptionentry.InvisibleChar = '•';
			this.table1.Add(this.descriptionentry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.descriptionentry]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.descriptionlabel = new global::Gtk.Label();
			this.descriptionlabel.Name = "descriptionlabel";
			this.descriptionlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Description:");
			this.descriptionlabel.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.descriptionlabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.descriptionlabel]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.titleentry = new global::Gtk.Entry();
			this.titleentry.CanFocus = true;
			this.titleentry.Name = "titleentry";
			this.titleentry.IsEditable = true;
			this.titleentry.InvisibleChar = '•';
			this.table1.Add(this.titleentry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.titleentry]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.titlelabel = new global::Gtk.Label();
			this.titlelabel.Name = "titlelabel";
			this.titlelabel.LabelProp = global::Mono.Unix.Catalog.GetString("Title:");
			this.table1.Add(this.titlelabel);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.titlelabel]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.updateurlentry = new global::Gtk.Entry();
			this.updateurlentry.CanFocus = true;
			this.updateurlentry.Name = "updateurlentry";
			this.updateurlentry.IsEditable = true;
			this.updateurlentry.InvisibleChar = '•';
			this.table1.Add(this.updateurlentry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.updateurlentry]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.updateurllabel = new global::Gtk.Label();
			this.updateurllabel.Name = "updateurllabel";
			this.updateurllabel.LabelProp = global::Mono.Unix.Catalog.GetString("Update URL:");
			this.updateurllabel.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.updateurllabel);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.updateurllabel]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.urlentry = new global::Gtk.Entry();
			this.urlentry.CanFocus = true;
			this.urlentry.Name = "urlentry";
			this.urlentry.IsEditable = true;
			this.urlentry.InvisibleChar = '•';
			this.table1.Add(this.urlentry);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.urlentry]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.urllabel = new global::Gtk.Label();
			this.urllabel.Name = "urllabel";
			this.urllabel.LabelProp = global::Mono.Unix.Catalog.GetString("URL:");
			this.urllabel.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.urllabel);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.urllabel]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.versionentry = new global::Gtk.Entry();
			this.versionentry.CanFocus = true;
			this.versionentry.Name = "versionentry";
			this.versionentry.IsEditable = true;
			this.versionentry.InvisibleChar = '•';
			this.table1.Add(this.versionentry);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.versionentry]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.versionlabel = new global::Gtk.Label();
			this.versionlabel.Name = "versionlabel";
			this.versionlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Version:");
			this.versionlabel.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add(this.versionlabel);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.versionlabel]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Internal child GTKFrontend.NewModDialog.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonCancel]));
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonOk]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.titleentry.Changed += new global::System.EventHandler(this.ontitletextchange);
		}
	}
}
