
// This file has been generated by the GUI designer. Do not modify.
namespace GTKFrontend
{
	public partial class GCWindow
	{
		private global::Gtk.VBox GCVBOX;

		private global::Gtk.HBox Outputbox;

		private global::Gtk.Label Outputlabel;

		private global::Gtk.Entry outputentry;

		private global::Gtk.Button outputbutton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKFrontend.GCWindow
			this.Name = "GTKFrontend.GCWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("GCWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GTKFrontend.GCWindow.Gtk.Container+ContainerChild
			this.GCVBOX = new global::Gtk.VBox();
			this.GCVBOX.Name = "GCVBOX";
			this.GCVBOX.Spacing = 6;
			// Container child GCVBOX.Gtk.Box+BoxChild
			this.Outputbox = new global::Gtk.HBox();
			this.Outputbox.Name = "Outputbox";
			this.Outputbox.Spacing = 6;
			// Container child Outputbox.Gtk.Box+BoxChild
			this.Outputlabel = new global::Gtk.Label();
			this.Outputlabel.Name = "Outputlabel";
			this.Outputlabel.LabelProp = global::Mono.Unix.Catalog.GetString("Output Directory");
			this.Outputbox.Add(this.Outputlabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.Outputbox[this.Outputlabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child Outputbox.Gtk.Box+BoxChild
			this.outputentry = new global::Gtk.Entry();
			this.outputentry.CanFocus = true;
			this.outputentry.Name = "outputentry";
			this.outputentry.IsEditable = true;
			this.outputentry.InvisibleChar = '•';
			this.Outputbox.Add(this.outputentry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.Outputbox[this.outputentry]));
			w2.Position = 1;
			// Container child Outputbox.Gtk.Box+BoxChild
			this.outputbutton = new global::Gtk.Button();
			this.outputbutton.CanFocus = true;
			this.outputbutton.Name = "outputbutton";
			this.outputbutton.UseStock = true;
			this.outputbutton.UseUnderline = true;
			this.outputbutton.Label = "gtk-open";
			this.Outputbox.Add(this.outputbutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.Outputbox[this.outputbutton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.GCVBOX.Add(this.Outputbox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.GCVBOX[this.Outputbox]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.GCVBOX);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
