
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ComboBox GameSelect;

	private global::Gtk.Button GameConfigSettings;

	private global::Gtk.Button Builder;

	private global::Gtk.Button Refresh;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Button New;

	private global::Gtk.Button Deleted;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView ModGrid;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView LogView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GameSelect = global::Gtk.ComboBox.NewText();
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 3"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 3 Portable"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 4"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 4 Golden"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 4 Dancing All Night"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 5"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 3 Dancing Moon Night"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona 5 Dancing Star Night"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona Q"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Persona Q2"));
		this.GameSelect.AppendText(global::Mono.Unix.Catalog.GetString("Catherine Full Body"));
		this.GameSelect.Name = "GameSelect";
		this.GameSelect.Active = 5;
		this.hbox1.Add(this.GameSelect);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GameSelect]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GameConfigSettings = new global::Gtk.Button();
		this.GameConfigSettings.CanFocus = true;
		this.GameConfigSettings.Name = "GameConfigSettings";
		this.GameConfigSettings.UseUnderline = true;
		this.GameConfigSettings.Label = global::Mono.Unix.Catalog.GetString("Settings");
		this.hbox1.Add(this.GameConfigSettings);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GameConfigSettings]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Builder = new global::Gtk.Button();
		this.Builder.CanFocus = true;
		this.Builder.Name = "Builder";
		this.Builder.UseUnderline = true;
		this.Builder.Label = global::Mono.Unix.Catalog.GetString("Build");
		this.hbox1.Add(this.Builder);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Builder]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Refresh = new global::Gtk.Button();
		this.Refresh.CanFocus = true;
		this.Refresh.Name = "Refresh";
		this.Refresh.UseUnderline = true;
		this.Refresh.Label = global::Mono.Unix.Catalog.GetString("Refresh");
		this.hbox1.Add(this.Refresh);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Refresh]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.hbox1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hseparator1]));
		w6.Position = 4;
		// Container child hbox1.Gtk.Box+BoxChild
		this.New = new global::Gtk.Button();
		this.New.CanFocus = true;
		this.New.Name = "New";
		this.New.UseUnderline = true;
		this.New.Label = global::Mono.Unix.Catalog.GetString("New");
		this.hbox1.Add(this.New);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.New]));
		w7.Position = 5;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Deleted = new global::Gtk.Button();
		this.Deleted.CanFocus = true;
		this.Deleted.Name = "Deleted";
		this.Deleted.UseUnderline = true;
		this.Deleted.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.hbox1.Add(this.Deleted);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Deleted]));
		w8.Position = 6;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ModGrid = new global::Gtk.NodeView();
		this.ModGrid.CanFocus = true;
		this.ModGrid.Name = "ModGrid";
		this.ModGrid.EnableSearch = false;
		this.ModGrid.Reorderable = true;
		this.GtkScrolledWindow.Add(this.ModGrid);
		this.vbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
		w11.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.LogView = new global::Gtk.TextView();
		this.LogView.CanFocus = true;
		this.LogView.Name = "LogView";
		this.LogView.Editable = false;
		this.LogView.CursorVisible = false;
		this.LogView.Overwrite = true;
		this.LogView.AcceptsTab = false;
		this.GtkScrolledWindow1.Add(this.LogView);
		this.vbox3.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow1]));
		w13.Position = 2;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 809;
		this.DefaultHeight = 672;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.WindowClose);
		this.GameSelect.Changed += new global::System.EventHandler(this.OnGameChange);
		this.GameConfigSettings.Clicked += new global::System.EventHandler(this.OnSettings);
		this.Builder.Clicked += new global::System.EventHandler(this.BuildButtonClick);
		this.Refresh.Clicked += new global::System.EventHandler(this.OnRefresh);
	}
}
